#' nsdm.savemap
#'
#' Save individual predictive maps to disk.
#'
#' @param maps A list of rasters (or a single raster) filled with predicted values, generated by `nsdm.map`.
#' @param save_path A character string specifying the directory where output maps will be saved.
#' @param species_name A character string indicating the name of the target taxon.
#' @param model_name A character string indicating the name of the target modeling algorithm.
#' @param format A character string specifying the file format(s) to save (`"rds"` for RDS files, `"tif"` for GeoTIFF, or `"both"` for both formats).
#'
#' @return This function does not return a value; it saves maps as `.rds` and/or `.tif` files in the specified directory.
#' @author Antoine Adde (antoine.adde@eawag.ch)
#' @export

nsdm.savemap <- function(maps, save_path, species_name, model_name = NULL, format = "both") {
  
  if (length(maps) == 0) {
    warning("No maps to save. Exiting function.")
    return(NULL)
  }
  
  # Handle ESM models
  if (model_name == "esm") {
    for (m in seq_along(maps)) {  # Safe iteration over maps
      map <- toMemory(maps[[m]])  # Ensure the raster is loaded in memory
      model_nameu <- names(maps)[m]
      
      # Define save path
      save_this_path <- file.path(save_path, species_name, model_name, model_nameu)
      suppressWarnings(dir.create(save_this_path, recursive = TRUE))
      
      # Define filenames
      f_fit_tif <- file.path(save_this_path, paste0(names(map), ".tif"))
      f_fit_rds <- file.path(save_this_path, paste0(names(map), ".rds"))
      
      # Save based on format
      if (format %in% c("both", "tif")) {
        tryCatch({
          suppressWarnings(
 writeRaster(map, f_fit_tif, filetype = "GTiff", datatype = "INT2U",
                   overwrite = TRUE, gdal = c("COMPRESS=LZW", "PREDICTOR=2"))
          )
        }, error = function(e) warning(paste("Failed to save TIFF:", f_fit_tif, "-", e$message)))
      }
      
      if (format %in% c("both", "rds")) {
        tryCatch({
          saveRDS(map, f_fit_rds, compress = TRUE)
        }, error = function(e) warning(paste("Failed to save RDS:", f_fit_rds, "-", e$message)))
      }
    }
    
  } else {  # Single-model case
    
    map <- toMemory(maps)  # Load raster completely in memory
    
    # Define save path
    save_this_path <- file.path(save_path, species_name, model_name)
    suppressWarnings(dir.create(save_this_path, recursive = TRUE))
    
    # Define filenames
    f_fit_tif <- file.path(save_this_path, paste0(names(map), ".tif"))
    f_fit_rds <- file.path(save_this_path, paste0(names(map), ".rds"))
    
    # Save based on format
    if (format %in% c("both", "tif")) {
      tryCatch({
        suppressWarnings(
 writeRaster(map, f_fit_tif, filetype = "GTiff", datatype = "INT2U",
                   overwrite = TRUE, gdal = c("COMPRESS=LZW", "PREDICTOR=2"))
        )
      }, error = function(e) warning(paste("Failed to save TIFF:", f_fit_tif, "-", e$message)))
    }
    
    if (format %in% c("both", "rds")) {
      tryCatch({
        saveRDS(map, f_fit_rds, compress = TRUE)
      }, error = function(e) warning(paste("Failed to save RDS:", f_fit_rds, "-", e$message)))
    }
  }
}
